# Generated by Django 5.0.3 on 2024-04-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proyecto_num_acuerdo_alter_empleado_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
