# Generated by Django 5.0.3 on 2024-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empleado_imagen_empleado_telefono_movil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(null=True, upload_to='empleados'),
        ),
    ]
