# Generated by Django 5.0.3 on 2024-04-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_empleado_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono_movil',
        ),
    ]
