# Generated by Django 5.0.3 on 2024-04-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_empleado_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_empleados/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto_dni',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_empleados/'),
        ),
    ]
