# Generated by Django 5.0.3 on 2024-04-05 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cliente_descripcion_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='empleados',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='empleado',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
