# Generated by Django 5.0.3 on 2024-04-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_proyecto_empleados_alter_tareas_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto_dni',
            field=models.ImageField(blank=True, null=True, upload_to='dni_empleados/'),
        ),
    ]
