# Generated by Django 5.0.3 on 2024-04-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_empleado_fecha_alta_alter_empleado_foto_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_alta',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('muy_alta', 'Muy Alta'), ('media', 'Media'), ('baja', 'Baja'), ('muy_baja', 'Muy Baja'), ('sin_prioridad', 'Sin Prioridad')], default='sin_prioridad', max_length=120, null=True),
        ),
    ]
