# Generated by Django 5.0.3 on 2024-04-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_empleado_foto_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_dni2',
            field=models.ImageField(blank=True, null=True, upload_to='dnis/'),
        ),
    ]
