# Generated by Django 5.0.3 on 2024-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cliente_archivos_alter_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
