# Generated by Django 5.0.3 on 2024-04-18 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='archivos',
        ),
        migrations.AddField(
            model_name='archivo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='media/archivos_clientes/'),
        ),
    ]
