# Generated by Django 5.0.3 on 2024-04-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_archivo_nombre_remove_cliente_archivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivos_clientes/'),
        ),
    ]
