# Generated by Django 5.0.3 on 2024-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_archivo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='descripcion',
            field=models.TextField(blank=True, default=models.FileField(upload_to='archivos_clientes/'), null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
