# Generated by Django 5.0.3 on 2024-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_archivo_descripcion_alter_archivo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
