# Generated by Django 5.0.3 on 2024-05-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='Proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.proyecto'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='Tareas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.tareas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('permanente', 'Permanente')], default='pendiente', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('muy_alta', 'Muy Alta'), ('media', 'Media'), ('baja', 'Baja'), ('muy_baja', 'Muy Baja'), ('sin_prioridad', 'Sin Prioridad')], default='sin_prioridad', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('permanente', 'Permanente')], default='pendiente', max_length=120, null=True),
        ),
    ]
