# Generated by Django 5.0.3 on 2024-05-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_archivo_proyecto_archivo_tareas_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creación', models.DateField(auto_now_add=True, null=True)),
                ('fecha_editado', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='archivo',
            name='tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.ticket'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1ª Justificacion', '1ª Justificacion'), ('2ª Justificacion', '2ª Justificacion'), ('Acuerdos', 'Acuerdos'), ('Diseño Gráfico', 'Diseño Gráfico'), ('E-Commerce', 'E-Commerce'), ('Factura electrónica', 'Factura electrónica'), ('Gestión Clientes', 'Gestión Clientes'), ('Gestión Procesos', 'Gestión Procesos'), ('Kit Digital', 'Kit Digital'), ('Marketing', 'Marketing'), ('Solicitud KD', 'Solicitud KD'), ('Redes Sociales', 'Redes Sociales'), ('SEO', 'SEO'), ('Web', 'Web'), ('TPV', 'TPV'), ('Diseño Gráfico', 'Diseño Gráfico'), ('URL', 'URL')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
