# Generated by Django 5.0.3 on 2024-05-20 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_delete_etiqueta_alter_ticketattachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='empleado',
        ),
        migrations.AddField(
            model_name='tareas',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
