# Generated by Django 5.0.3 on 2024-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_etiqueta_table_header_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='ticket',
            name='etiquetas',
            field=models.ManyToManyField(related_name='tickets', to='core.etiqueta'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
