# Generated by Django 5.0.3 on 2024-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_name_etiqueta_nombre_ticket_etiquetas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='etiquetas',
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
